### ISSUE TITLE
Unnecessary console.log,

### ISSUE THREAD

**Issue by emreguendogdu** [Xatta-Trone/medium-parser-extension#10]
Hi, as a developer and constant user of the Browser Console, I find 4 line of "not a medium blog" logs on each time and each page annoying and unnecessary. I think it would be better to get notified only on Medium, as other websites are unrelated to extension's job. 
Appreciate your work though, thank you!

**Comment by Xatta-Trone** [comment]
@emreguendogdu 

Hello, I have updated it based on your request. Please update the extension.

**Comment by emreguendogdu** [comment]
Thank you, updated it. Have a great night!

@Xatta-Trone
