### ISSUE TITLE
Can you also add support for ReadMedium.com ?

### ISSUE THREAD

**Issue by blacksev** [Xatta-Trone/medium-parser-extension#15]
[ReadMedium.com](https://readmedium.com) has a very clean view and also provide translations. It would be very helpful for non-native readers. You may just replace the domain to readmedium.com

**Comment by Xatta-Trone** [comment]
@blacksev I have a question. What do you use under the hood to pull the contents ? Is it google web cache ? And, it is a beautiful UI. I like it, also the translation feature too. Good work.

**Comment by Xatta-Trone** [comment]
@blacksev I will add your site to this extension. It's great work...thanks a lot.

**Comment by blacksev** [comment]
@Xatta-Trone Thanks a lot. Could you fix it by just keep the last path in the URL? The URL pattern in readmedium is like this: https://readmedium.com/exploring-djangos-extensibility-a-developer-s-tale-c076e713da65

**Comment by Xatta-Trone** [comment]
> @Xatta-Trone Thanks a lot. Could you fix it by just keep the last path in the URL? The URL pattern in readmedium is like this: https://readmedium.com/exploring-djangos-extensibility-a-developer-s-tale-c076e713da65

@blacksev I see...in the next update I will update this one. thank you.

**Comment by blacksev** [comment]
> > @Xatta-Trone Thanks a lot. Could you fix it by just keep the last path in the URL? The URL pattern in readmedium is like this: https://readmedium.com/exploring-djangos-extensibility-a-developer-s-tale-c076e713da65
> 
> @blacksev I see...in the next update I will update this one. thank you.

Ah, I found ReadMedium has fixed the issue. Still thanks for your quick reply.
