### ISSUE TITLE
Unrecognized manifest key 'browser_specific_settings'.

### ISSUE THREAD

**Issue by dheerajawale-svg** [Xatta-Trone/medium-parser-extension#18]
Gives below error during installation of extension.

  "browser_specific_settings": {
    "gecko": {
      "id": "medium-parser@example.com"
    }
  }

**Comment by Xatta-Trone** [comment]
It is a setting for Mozilla add-on. It will show an error in chrome, but the extension will work perfectly. 
Please install these from the chrome web store.  https://chromewebstore.google.com/detail/medium-parser/egejbknaophaadmhijkepokfchkbnelc

**Comment by Xatta-Trone** [comment]
@dheerajawale-svg Hello, I have removed the key which was giving the error. The latest update just got published. Could you please give it a try and see if it works? https://chromewebstore.google.com/detail/medium-parser/egejbknaophaadmhijkepokfchkbnelc?hl=en
