### ISSUE TITLE
Menu show in Explore topics and each topic page 

### ISSUE THREAD

**Issue by alvin96** [Xatta-Trone/medium-parser-extension#21]
![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/20142859/f4517af1-f4a2-4266-bcf3-c158e4aa3154)

/explore-topics
/tag/*

**Comment by Xatta-Trone** [comment]
@alvin96 thank you for bringing it out. I will release an update shortly.

**Comment by alvin96** [comment]
> @alvin96 thank you for bringing it out. I will release an update shortly.

Thanks for the fast response, really appreciate it✨

**Comment by alvin96** [comment]
![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/20142859/6feb33e3-1c8c-4ade-ad5f-31c0d67eae29)


https://medium.com/@medium

 I found user profile page (pages start with "@") also have the same issue too.

**Comment by Xatta-Trone** [comment]
@alvin96 Thank you very much for bringing it up. I have patched the fixes and submitted it for review on chrome and Mozilla. It will be available in 2-3 days.  Thank you again.

**Comment by alvin96** [comment]
@Xatta-Trone Welcome, thanks for the amazing plugin too !!

**Comment by Xatta-Trone** [comment]
@alvin96 
Published: https://chromewebstore.google.com/detail/medium-parser/egejbknaophaadmhijkepokfchkbnelc?hl=en thank you.

**Comment by alvin96** [comment]
It works like a charm!! Thanks again!!!
