### ISSUE TITLE
There should be a simple customization option

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [Xatta-Trone/medium-parser-extension#23]
This extension is great but needs some simple customizations. It would be great if it offered 3 different sizes like now large, medium and small.

**Comment by Xatta-Trone** [comment]
@T-a-c-h-y-o-n You mean the button sizes ?

**Comment by T-a-c-h-y-o-n** [comment]
Exactly, because in its current form it can be confused with text.

**Comment by T-a-c-h-y-o-n** [comment]
You may also be given the option of taking it to the left side.

**Comment by Xatta-Trone** [comment]
65% of current size 
![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/e4fe5720-6710-4fe4-b8cc-21d7296ff96a)

80% of current size 
![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/ced31d6f-c600-45c7-a939-b08bcaece72a)

Do you think it is readable ? Or could you please suggest some UI/sizes ? Thank you.

**Comment by Xatta-Trone** [comment]
@T-a-c-h-y-o-n

**Comment by Xatta-Trone** [comment]
Obviously, the button sizes will be small too... I just wanted to resonate about the text sizes (if it is readable or not, to make sense). 
Movement to the left, right can be done. However, I have other jobs right now. Therefore, can not work on it right away. I will keep the changes in mind for the next update. In the meantime, if you could do these changes and create a PR, I would gladly accept.

**Comment by T-a-c-h-y-o-n** [comment]
Even just the black background becomes smaller. In other words, the text remains the same, but the black area it covers becomes smaller.. There's no rush anyway. It still works in its current form. Thanks for your effort.
