### ISSUE TITLE
Can you add support for MS EDGE addon store? 

### ISSUE THREAD

**Issue by BiponD97** [Xatta-Trone/medium-parser-extension#30]
Please can you make a extension support for edge store?
I know Windows Edge supports chrome store extension but now Edge Canary for Android too supports Extension Install by id (only from edge store) ! 

So can you make it possible have Medium Parser extension available independently for Edge Store, please!

**Comment by Xatta-Trone** [comment]
@BiponD97 I see...thank you for bringing it up. I will publish it to the edge store and notify you here.

**Comment by BiponD97** [comment]
> @BiponD97 I see...thank you for bringing it up. I will publish it to the edge store and notify you here.

Thanks much appreciated ❤️

**Comment by Xatta-Trone** [comment]
@BiponD97 I tried to publish in the Edge store, but it got rejected. Sorry. 

![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/9ae03340-e8bc-4cfc-97b9-09f754dc92bc)
