### ISSUE TITLE
Manifest file is missing or unreadable. Could not load manifest. 

### ISSUE THREAD

**Issue by gonzaloamadio** [Xatta-Trone/medium-parser-extension#34]
**Describe the bug**
Followed steps, but got this error:

```
Error
Manifest file is missing or unreadable
Could not load manifest.
```

**To Reproduce**
Just follow steps to install

**Expected behavior**
Extension to be installed

**Screenshots**
<img width="489" alt="image" src="https://github.com/Xatta-Trone/medium-parser-extension/assets/1005027/9a82d025-376c-4b5e-a087-a73e7ffbc847">
<img width="489" alt="image" src="https://github.com/Xatta-Trone/medium-parser-extension/assets/1005027/9a82d025-376c-4b5e-a087-a73e7ffbc847">

**Desktop (please complete the following information):**
 - OS: Sonoma 14.5
 - Browser Chrome 
 - Version  125.0.6422.142 (Official Build) (arm64)

**Comment by Xatta-Trone** [comment]
@gonzaloamadio 
I think you missed the last step....the `chrome` and `firefox` have their dedicated folder now.

Install manually
1. Download this repo as a [ZIP file from GitHub](https://github.com/Xatta-Trone/medium-parser-extension/archive/refs/heads/main.zip).
1. Unzip the file and you should have a folder named `medium-parser-extension-main`.
1. In Chrome/Edge go to the extensions page (`chrome://extensions` or `edge://extensions`).
1. Enable Developer Mode by clicking the toggle button on the top right side of the browser.
1. Drag the `chrome` folder anywhere on the page to import it (do not delete the folder afterward).

Or you can just install from the dev store 
https://chromewebstore.google.com/detail/medium-parser/bdkfodcnmgegolifeafnpbgjnjfohado
https://addons.mozilla.org/en-US/firefox/addon/medium-parser/

**Comment by gonzaloamadio** [comment]
Ah nice, I drag the chrome folder and looks ok
