### ISSUE TITLE
[BUG]: No longer working on Mozilla Firefox

### ISSUE THREAD

**Issue by ianTevesAcc** [Xatta-Trone/medium-parser-extension#35]
**Describe the bug**
New UI update of Medium disables Medium Parser UI on Firefox.

**To Reproduce**
1. Install Firefox and Medium
2. Go to a restricted and paid page in medium

**Expected behavior**
The medium parser buttons to appear on the top right, but are now missing.

**Screenshots**
![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/105651670/139b7267-9564-4a8a-896c-97374923fb65)

**Desktop:**
 - OS: Windows
 - Browser: Firefox
 - Version: 127.0

**Comment by Xatta-Trone** [comment]
@ianTevesAcc 

1. Click on the extension to open the settings page 
2. Select `show options in page`
3. Click save changes


![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/79e0fa16-9051-47ce-8454-fb443e077310)


let me know if it works.

**Comment by ianTevesAcc** [comment]
@Xatta-Trone 
It's not working on my end. I tried each option actually and all of them didn't work. It seems like it can't identify that its a medium page? I dont know.

![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/105651670/c821e6c8-59fc-4d69-b718-b704823f665b)

**Comment by Xatta-Trone** [comment]
@ianTevesAcc So sorry to hear that...could you please make the settings like this and try again? I think the access to all website permission was revoked for some reason. 

![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/803dec3c-6922-45b4-b291-a1fcde1a56c6)
![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/9893ac88-deb0-438e-9b7a-eb5e4f2c1324)

**Comment by ianTevesAcc** [comment]
That solved it! Thank you so much for the help!
