### ISSUE TITLE
Is that possible one specific page not working?

### ISSUE THREAD

**Issue by ryankert01** [Xatta-Trone/medium-parser-extension#7]
First, I wanna say it's an amazing work!!!

But, this page is not working for me.

http://webcache.googleusercontent.com/search?q=cache:https://medium.com/momo%E7%9A%84%E6%A9%9F%E5%99%A8%E4%BA%BA%E7%95%99%E5%AD%B8%E5%A4%A2/why-i-no-longer-set-goals-850e131076f0&strip=0&vwsrc=1&referer=medium-parser

![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/91534261/cb2402ea-fb52-4df9-9ab6-a4dd0bb8f624)

**Comment by Xatta-Trone** [comment]
@ryankert01 could you please send me the original medium link ? I tried to copy and paste the link, but it was not working.

**Comment by ryankert01** [comment]
https://medium.com/momo%E7%9A%84%E6%A9%9F%E5%99%A8%E4%BA%BA%E7%95%99%E5%AD%B8%E5%A4%A2/why-i-no-longer-set-goals-850e131076f0

it contains chinese-traditional

**Comment by ryankert01** [comment]
By the way, I'm using version from chrome extension store, and use it on Edge. So far, I have only encountered 1 or 2 post cannot read, and the Archive.is option is just loading forever.

**Comment by Xatta-Trone** [comment]
https://archive.is/kL9BB

@ryankert01 archive.is link

**Comment by Xatta-Trone** [comment]
google one was not working.

**Comment by Xatta-Trone** [comment]
> By the way, I'm using version from chrome extension store, and use it on Edge. So far, I have only encountered 1 or 2 post cannot read, and the Archive.is option is just loading forever.

Yeah. Not all the link works. The most recently added articles take some time to be cached by google.

**Comment by ryankert01** [comment]
How to get that link?

My archive.is option is loading forever, lol.

**Comment by Xatta-Trone** [comment]
> How to get that link?
> 
> My archive.is option is loading forever, lol.

I just clicked and it worked. Maybe some network issue.

**Comment by ryankert01** [comment]
Okay, 👌.

Nice work!!! Appreciate it.
