### ISSUE TITLE
How to support custom website?

### ISSUE THREAD

**Issue by zhl111** [Xatta-Trone/medium-parser-extension#8]
for example：https://www.caixinglobal.com/2023-11-06/chart-of-the-day-china-basic-pension-funds-record-low-returns-102125274.html

**Comment by Xatta-Trone** [comment]
Option 1:

You can fork this repo and modify it according to your needs. 

Option 2:
You can directly read the contents from [archive.is](https://archive.is/)

![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/6b4bafd0-412f-4427-a7bd-d1af3e23e751)

**Comment by Xatta-Trone** [comment]
Sorry, can not help on this. The extension was based on medium and medium based site. Also, the website you have mentioned is not cached by google or archive.is. Therefore, this extension is useless.
